spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
logstash:
  host: localhost
  port: 50000
  enable: true